input {
  file {
    path => "/workspace/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "flask-logs-%{+YYYY.MM.dd}"
  }
}
